# Settings for Interactive deduplication of fullsized Images
deduplication:
  method: "dhash" 
  hash_size: 8
  similarity_threshold: 8  

# Settings for the Sliding Window Algorithm that creates the patches from fullsized images
patch_creation:
  # Output Settings
  target_size: 256    # Width and Height Patches
  
  # Scaling logic
  scale_divisors: [1.5, 2.0, 3.0, 4.0, 6.0, 8.0]  # image_height / divisor = initial patch size (gets rescaled to target_size)
  overlap: 0.5                                    # How much neighboring Patches overlap (0: no overlap, 0.8: 80% overlap)
  use_relative_min_size: true                     
  min_relative_factor: 0.15
  absolute_pixel_floor: 128                       # image_height / divisor must be greater than this for the patche to valid

  # Class IDs 
  class_ids:
    qr_code: 1
    distractor: 0

  # IoU / Containment Thresholds
  thresholds:
    qr_positive: 0.85     # How much of a QR-Code must be inside the patch for the patch to be counted as "positive"
    qr_ambiguous: 0.10    # Patche with containment above this and below qr_positive are marked as ambiguous and discarded.
    qr_min_coverage: 0.03 # How much of the Patch needs to covered with a QR-Code for the patch to be counted as "positive"
    distractor: 0.20      # How much of a distractor needs to be inside a patch for the patch to be counted as "hard negative"

  # Texture Filtering & Sampling Rates
  sampling:
    keep_rate_distractor: 0.6  # How much percent of the "hard negative" patches to keep
    texture_threshold: 25.0    # StdDev, below this a patche is considered as "Flat" above this as "Textured"
    keep_rate_flat: 0.08      # How much of the "Flat" patches to keep
    keep_rate_textured: 0.02   # How much of the "Textured" backgrounds to keep

# Settings for the Synthetic Data Generator
generation:
  img_size: 256   # The size in pixels of the pathches to be generated
  
  # Lighting (Subtle gradients)
  lighting_slope_range: [-0.001, 0.001]
  lighting_base_range: [0.8, 1.2]
  
  # QR Appearance
  qr_dark_range: [0, 80]       # Dark pixels (0=Black)
  qr_light_range: [180, 255]   # Light pixels (255=White)
  qr_invert_prob: 0.1          # Chance of inverting a QR-Code (white on black)
  qr_color_prob: 0.2           # Chance of generating a colorful qr code
  
  # Geometry (Geometric Augmentations)
  qr_perspective_range: [0.8, 1.0]    # How much the QR-Code is skewed
  qr_rotation_range: [-180, 1180]     # How much the QR-Cod is rotated
  
  # Placement & Scaling
  min_scale: 0.2               # How big the qr code must be compared to the patch area
  max_scale: 1.2               # How big the qr code is allowed to be compared to the patch area
  placement_retries: 25        # How often the generator retries to recreate the patch, in case one of the rules were broken.
  min_visible_percent: 0.7     # How much of the qr code must be visible inside the patch

# Settings for splitting the dataset in train, validation and test
split:
  train: 0.9
  val: 0.098
  test: 0.002