# Project Settings
project:
  name: "qr_classifier"         # Name of the project
  run_name: "run_01_baseline"   # Name of the iteration of the model
  seed: 42                      # Random seed for reproducability

# Dataset Settings
data:
  dataset_path: "data/processed_patches"  # Where the dataset to use is stored relative to the project root
  img_height: 256                         # Height of the input images
  img_width: 256                          # Width of the input images
  channels: 1                             # Channels of the input images
  batch_size: 32                          # Batch size used for training

# Model Architecture Settings
model:
  input_shape: [256, 256, 1]    # Input shape to the model
  type: "transfer"              # Typ of model to use. Either "custom" or "transfer"
                                # if "custom", the defined architecture in the layers section is used
                                # if "transfer", the convolutional layers defined in the layers section are ignored
                                # The "Classifier Head" must be specified in all cases.

  # Settings for the transfer model, if enabled
  transfer:
    base_model: "EfficientNetB0"  # Name of the Transfer Model. Models currently supported are:
                                    # MobileNetV3Small
                                    # MobileNetV2
                                    # EfficientNetB0

    freeze_base: false            # true: Pretrained weights of the models convolutional blocks will not be adjusted
                                  # flase: Pretrained weight of the models convolutional blocks will be retrained
  
  # Layers to be used in the model
  layers:
    ### --- Data Augmentation ---  
    # 1. Geometry (Spatial Robustness)
    - type: "random_flip"
      mode: "horizontal_and_vertical"
      
    - type: "random_rotation"
      factor: 0.1

    # 2. Artifacts & Quality (Texture Robustness)
    # Adds random grain/static. Simulates "dots/artifacts".
    - type: "gaussian_noise"
      stddev: 0.025   # Amount of noise (0.1 is moderate grain)

    # Changes contrast. Simulates "Blur" or bad lighting
    # by reducing the sharpness of edges.
    - type: "random_contrast"
      factor: 0.1

    # --- CNN ARCHITECTURE ---
    # Block 1
    - type: "conv"
      filters: 32
      kernel_size: 3
      padding: "same"
      activation: "relu"
      batch_norm: true
    - type: "max_pool"
      pool_size: 2

    # Block 2
    - type: "conv"
      filters: 64
      kernel_size: 3
      padding: "same"
      activation: "relu"
      batch_norm: true
    - type: "max_pool"
      pool_size: 2

    # Block 3
    - type: "conv"
      filters: 128
      kernel_size: 3
      padding: "same"
      activation: "relu"
      batch_norm: true
    - type: "max_pool"
      pool_size: 2

    # Block 4
    - type: "conv"
      filters: 128
      kernel_size: 3
      padding: "same"
      activation: "relu"
      batch_norm: true
    - type: "max_pool"
      pool_size: 2

    # Block 5
    - type: "conv"
      filters: 128
      kernel_size: 3
      padding: "same"
      activation: "relu"
      batch_norm: true
    - type: "max_pool"
      pool_size: 2

    ### --- Classifier Head ---
    - type: "global_avg_pool"
    
    - type: "dense"
      units: 64
      activation: "relu"
      
    - type: "dropout"
      rate: 0.5

    - type: "dense"
      units: 1
      activation: "sigmoid"

# Hyperparameters for training
train:
  epochs: 50                                    # How many epochs to train for
  learning_rate: 0.00005                        # The initial learning rate
  optimizer: "adam"                             # The optimizer to be used
  loss: "binary_crossentropy"                   # The loss function to be used
  metrics: ["accuracy", "Precision", "Recall"]  # The metrics to monitor during training
  
  # Callback settings
  callbacks:
    early_stopping_patience: 8    # Stop the training when val_loss hasn't improved after this amount of episodes
    save_best_only: true          # Wheter to save the models after each epoch or only save when performance is improved
    
    use_lr_scheduler: true        # Wheter the learning rate should be adjusted during training
    reduce_lr_patience: 4         # Lower the learning rate when no improvements were made after this amount of epochs
    reduce_lr_factor: 0.5         # How much to multiply the current learning rate by when the scheduler is triggered
    reduce_lr_min: 0.000001       # Minimum value fot he learning rate. (It is no recommended to go below this value)